In [43]:
import numpy as np

def vandermonde_matrix(vector, N=None, increasing=False):
    if N is None:
        N = len(vector)
    if increasing:
        matrix = np.array([x**i for i in range(N) for x in vector]).reshape(len(vector), N)
    else:
        matrix = np.array([x**(N-1-i) for i in range(N) for x in vector]).reshape(len(vector), N)
    return matrix

vector = [1, 2, 3, 4]
print("Vandermonde matrix (increasing):")
print(vandermonde_matrix(vector, increasing=True))

print("\nVandermonde matrix (decreasing):")
print(vandermonde_matrix(vector, increasing=False))


Vandermonde matrix (increasing):
[[ 1  1  1  1]
 [ 1  2  3  4]
 [ 1  4  9 16]
 [ 1  8 27 64]]

Vandermonde matrix (decreasing):
[[ 1  8 27 64]
 [ 1  4  9 16]
 [ 1  2  3  4]
 [ 1  1  1  1]]


In [44]:
def moving_average(sequence, k):
    n = len(sequence)
    if k > n:
        return []
    moving_averages = []
    for i in range(n - k + 1):
        window = sequence[i:i + k]
        window_average = sum(window) / k
        moving_averages.append(window_average)
    return moving_averages

sequence = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k = 3
print("Moving averages:")
print(moving_average(sequence, k))


Moving averages:
[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
